# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvndrawC <- function(mu, sig) {
    .Call('_fattvpVAR_mvndrawC', PACKAGE = 'fattvpVAR', mu, sig)
}

#' @export
carterkohn <- function(y, Z, Ht, Qt, m, p, t, B0, V0) {
    .Call('_fattvpVAR_carterkohn', PACKAGE = 'fattvpVAR', y, Z, Ht, Qt, m, p, t, B0, V0)
}

alphahelper <- function(y, Z, Btdraw) {
    .Call('_fattvpVAR_alphahelper', PACKAGE = 'fattvpVAR', y, Z, Btdraw)
}

sigmahelper1 <- function(Atdraw, M) {
    .Call('_fattvpVAR_sigmahelper1', PACKAGE = 'fattvpVAR', Atdraw, M)
}

sigmahelper2 <- function(capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_fattvpVAR_sigmahelper2', PACKAGE = 'fattvpVAR', capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

#' @export
sigmahelper4 <- function(y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_fattvpVAR_sigmahelper4', PACKAGE = 'fattvpVAR', y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

sigmahelper3 <- function(capAt, sigt) {
    .Call('_fattvpVAR_sigmahelper3', PACKAGE = 'fattvpVAR', capAt, sigt)
}

getvc <- function(Ht) {
    .Call('_fattvpVAR_getvc', PACKAGE = 'fattvpVAR', Ht)
}

makeregs_fcC <- function(ydat, p) {
    .Call('_fattvpVAR_makeregs_fcC', PACKAGE = 'fattvpVAR', ydat, p)
}

mz <- function(n) {
    .Call('_fattvpVAR_mz', PACKAGE = 'fattvpVAR', n)
}

meye <- function(n) {
    .Call('_fattvpVAR_meye', PACKAGE = 'fattvpVAR', n)
}

vechC <- function(x) {
    .Call('_fattvpVAR_vechC', PACKAGE = 'fattvpVAR', x)
}

getfcsts <- function(Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p) {
    .Call('_fattvpVAR_getfcsts', PACKAGE = 'fattvpVAR', Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p)
}

wishdrawC <- function(h, n) {
    .Call('_fattvpVAR_wishdrawC', PACKAGE = 'fattvpVAR', h, n)
}

makeregs2_fcC <- function(dat, p) {
    .Call('_fattvpVAR_makeregs2_fcC', PACKAGE = 'fattvpVAR', dat, p)
}

matmult <- function(x, nt) {
    .Call('_fattvpVAR_matmult', PACKAGE = 'fattvpVAR', x, nt)
}

varfcst <- function(b, sig, y, nf) {
    .Call('_fattvpVAR_varfcst', PACKAGE = 'fattvpVAR', b, sig, y, nf)
}

